version: "3.7"

services:
  mongodb:
    image: "mongo:4.2"
    volumes: 
      - mongo:/data/db
    ports:
      - 27017:27017
    expose:
      - 27017

  node:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/myTasks

volumes: 
  mongo: